-- locação exemplo
IF NOT EXISTS (SELECT 1 FROM dbo.LOCACAO WHERE QR_CODE = 'QR-LOC-0001')
INSERT INTO dbo.LOCACAO (CONDICAO_ENTREGA, DATA_SAIDA, QR_CODE, CLIENTE_ID, MOTO_ID)
VALUES ('OK', SYSUTCDATETIME(), 'QR-LOC-0001', 1, 1);
GO

-- registros exemplo
INSERT INTO dbo.REGISTRO_MOTO_PATIO (DATA_HORA_REGISTRO, SETOR, TIPO, VAGA, MOTO_ID)
VALUES (SYSUTCDATETIME(), 'A', 'ENTRADA', 'A1', 1);
GO

INSERT INTO dbo.REGISTRO_MOTO_PATIO (DATA_HORA_REGISTRO, SETOR, TIPO, VAGA, MOTO_ID)
VALUES (SYSUTCDATETIME(), 'A', 'SAIDA',   'A1', 1);
GO

INSERT INTO dbo.REGISTRO_MOTO_PATIO (DATA_HORA_REGISTRO, SETOR, TIPO, VAGA, MOTO_ID)
VALUES (SYSUTCDATETIME(), 'B', 'ENTRADA', 'B2', 2);
GO
