-- Criação da tabela de eventos de integração
CREATE TABLE integration_events (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    source      VARCHAR(50)   NOT NULL,
                                    type        VARCHAR(80)   NOT NULL,
                                    event_ts    TIMESTAMP     NULL,
                                    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    data        VARCHAR(4000) NULL
);

-- Índices para melhorar consultas por data e tipo
CREATE INDEX ix_integration_events_created_at ON integration_events (created_at);
CREATE INDEX ix_integration_events_type       ON integration_events (type);
