CREATE INDEX IDX_CLIENTE_CPF           ON CLIENTE(CPF);
CREATE INDEX IDX_MOTO_PLACA            ON MOTO(PLACA);
CREATE INDEX IDX_LOCACAO_CLIENTE       ON LOCACAO(CLIENTE_ID);
CREATE INDEX IDX_LOCACAO_MOTO          ON LOCACAO(MOTO_ID);
CREATE INDEX IDX_LOCACAO_DATA_SAIDA    ON LOCACAO(DATA_SAIDA);
CREATE INDEX IDX_REGISTRO_MOTO         ON REGISTRO_MOTO_PATIO(MOTO_ID);
