IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_CLIENTE_CPF' AND object_id = OBJECT_ID('dbo.CLIENTE'))
CREATE INDEX IDX_CLIENTE_CPF ON dbo.CLIENTE(CPF);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_MOTO_PLACA' AND object_id = OBJECT_ID('dbo.MOTO'))
CREATE INDEX IDX_MOTO_PLACA ON dbo.MOTO(PLACA);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_LOCACAO_CLIENTE' AND object_id = OBJECT_ID('dbo.LOCACAO'))
CREATE INDEX IDX_LOCACAO_CLIENTE ON dbo.LOCACAO(CLIENTE_ID);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_LOCACAO_MOTO' AND object_id = OBJECT_ID('dbo.LOCACAO'))
CREATE INDEX IDX_LOCACAO_MOTO ON dbo.LOCACAO(MOTO_ID);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_LOCACAO_DATA_SAIDA' AND object_id = OBJECT_ID('dbo.LOCACAO'))
CREATE INDEX IDX_LOCACAO_DATA_SAIDA ON dbo.LOCACAO(DATA_SAIDA);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IDX_REGISTRO_MOTO' AND object_id = OBJECT_ID('dbo.REGISTRO_MOTO_PATIO'))
CREATE INDEX IDX_REGISTRO_MOTO ON dbo.REGISTRO_MOTO_PATIO(MOTO_ID);
GO
