DELETE FROM MOTO
WHERE ID IN (
    SELECT ID FROM (
                       SELECT ID, ROW_NUMBER() OVER (PARTITION BY PLACA ORDER BY ID) AS RN
                       FROM MOTO
                   ) X
    WHERE X.RN > 1
);

DELETE FROM MOTO
WHERE ID IN (
    SELECT ID FROM (
                       SELECT ID, ROW_NUMBER() OVER (PARTITION BY CHASSI ORDER BY ID) AS RN
                       FROM MOTO
                   ) X
    WHERE X.RN > 1
);

CREATE UNIQUE INDEX IF NOT EXISTS UX_MOTO_PLACA  ON MOTO(PLACA);
CREATE UNIQUE INDEX IF NOT EXISTS UX_MOTO_CHASSI ON MOTO(CHASSI);

CREATE INDEX IF NOT EXISTS IDX_MOTO_STATUS ON MOTO(STATUS);
CREATE INDEX IF NOT EXISTS IDX_MOTO_MODELO ON MOTO(MODELO);

CREATE UNIQUE INDEX IF NOT EXISTS UX_CLIENTE_EMAIL ON CLIENTE(EMAIL);
