IF COL_LENGTH('dbo.LOCACAO', 'CONDICAO_DEVOLUCAO') IS NOT NULL
ALTER TABLE dbo.LOCACAO ALTER COLUMN CONDICAO_DEVOLUCAO VARCHAR(255) NULL;
GO

IF COL_LENGTH('dbo.LOCACAO', 'CONDICAO_ENTREGA') IS NOT NULL
ALTER TABLE dbo.LOCACAO ALTER COLUMN CONDICAO_ENTREGA VARCHAR(255) NULL;
GO
